// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // SUBSTITUA 'seu-project-id-aqui' pelo ID real do seu projeto
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDummyKey-WebVersion-ChangeThis',
    appId: '1:123456789012:web:abcdef123456789012',
    messagingSenderId: '123456789012',
    projectId: 'fazenda-santa-fe-c0afa', // ← MUDE AQUI
    authDomain: 'fazenda-santa-fe-c0afa.firebaseapp.com', // ← MUDE AQUI
    storageBucket: 'fazenda-santa-fe-c0afa.appspot.com', // ← MUDE AQUI
  );

  // SUBSTITUA 'seu-project-id-aqui' pelo ID real do seu projeto
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDummyKey-AndroidVersion-ChangeThis',
    appId: '1:123456789012:android:1234567890123456',
    messagingSenderId: '123456789012',
    projectId: 'fazenda-santa-fe-c0afa', // ← MUDE AQUI
    storageBucket: 'fazenda-santa-fe-c0afa.appspot.com', // ← MUDE AQUI
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDummyKey-iOSVersion-ChangeThis',
    appId: '1:123456789012:ios:1234567890123456',
    messagingSenderId: '123456789012',
    projectId: 'fazenda-santa-fe-c0afa', // ← MUDE AQUI
    storageBucket: 'fazenda-santa-fe-c0afa.appspot.com', // ← MUDE AQUI
    iosClientId: '123456789012-abcdefghijklmnop.apps.googleusercontent.com',
    iosBundleId: 'com.fazenda.santafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummyKey-iOSVersion-ChangeThis',
    appId: '1:123456789012:ios:1234567890123456',
    messagingSenderId: '123456789012',
    projectId: 'fazenda-santa-fe-c0afa', // ← MUDE AQUI
    storageBucket: 'fazenda-santa-fe-c0afa.appspot.com', // ← MUDE AQUI
    iosClientId: '123456789012-abcdefghijklmnop.apps.googleusercontent.com',
    iosBundleId: 'com.fazenda.santafe',
  );
}
